# Generated by Django 4.2.3 on 2023-07-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_subcategory_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(default='exit', max_length=10),
            preserve_default=False,
        ),
    ]
