# Generated by Django 4.2.3 on 2023-07-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_des_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='total_tk',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
