# Generated by Django 4.2 on 2023-08-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_customerorder_total_tk'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='transaction_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
