# Generated by Django 4.2 on 2023-08-21 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_orderitem_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='orderItems',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.orderitem'),
        ),
    ]
