# Generated by Django 4.2 on 2023-08-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_customerorder_orderitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='orderItems',
        ),
        migrations.AddField(
            model_name='customerorder',
            name='orderItems',
            field=models.ManyToManyField(blank=True, to='myapp.orderitem'),
        ),
    ]
