# Generated by Django 4.2.5 on 2023-09-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_category_image_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hot_product',
            field=models.BooleanField(default=False),
        ),
    ]
