# Generated by Django 4.2.5 on 2023-09-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_product_hot_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='special_collection',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='special_discount',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='hot_product',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
