# Generated by Django 4.2.5 on 2023-09-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_category_special_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='special_discount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
