# Generated by Django 4.2.5 on 2023-09-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_category_special_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='any_special_discount',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
