# Generated by Django 4.2.6 on 2023-11-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_product_image2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuppon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuppon_name', models.CharField(max_length=10)),
            ],
        ),
    ]
