# Generated by Django 4.2.6 on 2023-11-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_cuppon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuppon',
            name='percent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
