# Generated by Django 4.2.6 on 2023-11-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_cuppon_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='after_using_coupn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='any_coupon',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
