# Generated by Django 4.2.6 on 2023-11-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_order_after_using_coupn_order_any_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
