# Generated by Django 4.2.6 on 2023-11-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_customerorder_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='orderItem',
            field=models.CharField(max_length=500),
        ),
    ]
