# Generated by Django 4.2.6 on 2023-11-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_customerorder_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='orderItem',
        ),
        migrations.AddField(
            model_name='customerorder',
            name='twoDAr',
            field=models.CharField(blank=True, default=None, max_length=500),
        ),
    ]
