# Generated by Django 4.2.7 on 2023-12-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_price',
            field=models.IntegerField(default=0),
        ),
    ]
