# Generated by Django 4.2.7 on 2023-12-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_product_main_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
