# Generated by Django 4.2.7 on 2023-12-28 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_remove_product_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='superCategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
